# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [ commit, push ]
default_language_version:
  python: python3.8
repos:
  - repo: https://github.com.cnpmjs.org/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
        name: 检查yaml文件是否合规
      - id: check-added-large-files
        name: 检查是否提交了超大文件
      - id: check-merge-conflict
        name: 检查是否含有未解决的冲突

  - repo: https://github.com.cnpmjs.org/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
      - id: gitlint
        name: "检查commit message是否符合  (add|mod|del|fix):.*"
  - repo: local
    hooks:
      - id: isort
        name: "imports自动格式化"
        entry: isort
        language: python
        types: [ python ]
        args:
          [
              "--multi-line=3",
              "--trailing-comma",
              "--force-grid-wrap=0",
              "--use-parentheses",
              "--line-width=120",
          ]
  - repo: https://github.com.cnpmjs.org/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        name: "代码风格格式化"
        args: [ "--line-length=120", "--target-version=py38" ]
  - repo: https://github.com.cnpmjs.org/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        # 在black格式化之后再触发flake8
        name: flake8检查
        args:
          [
              "--max-line-length=120",
              "--exclude=__init__.py",
              "--ignore=E203,E501,W503,W291,E402",
          ]
